name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore .\PicSelect\PicSelect.csproj

      - name: Build app
        run: dotnet build .\PicSelect\PicSelect.csproj -c Release --no-restore

      - name: Run core tests
        run: dotnet test .\PicSelect.Core.Tests\PicSelect.Core.Tests.csproj -c Release --no-restore
